### ISSUE TITLE
help with bloomapi / letsencrypt-gcloud-balancer

### ISSUE THREAD

**Issue by kostukp96** [bloomapi/letsencrypt-gcloud-balancer#5] opened 2020-12-31 09:22 UTC
Hello! I am found on "stackoverflow"  this question https://stackoverflow.com/questions/47337817/how-to-setup-letsencrypt-for-google-cloud-compute-engine-load-balancer. You write to solve this problem you need to use "loud function + cloud scheduler + https://github.com/bloomapi/letsencrypt-gcloud-balancer". Could you explain in more detail how exactly to run a docker file from your repository?
Thank you!

**Comment by untoldone** [comment] 2020-12-31 16:27
The readme at https://github.com/bloomapi/letsencrypt-gcloud-balancer/blob/master/README.md has details on how to run the container. If you have more specific questions on the readme, if something isn't working, or if something is unclear, let me know.

Will close this for now as it isn't a code issue.

**Closed as completed by untoldone** 2020-12-31 16:27 UTC

**Comment by kostukp96** [comment] 2020-12-31 17:30
For run this dockerfile, i need to creat cloud run or cloud functions ?

**Comment by untoldone** [comment] 2020-12-31 21:04
It sounds like you may be using this with other technologies I'm not familiar with / might not be able to help with. The instructions provided in the readme are for if you run it in docker directly -- it is already pushed to dockerhub, so you don't need to do anything with the dockerfile yourself unless you plan to change the container in some way.

**Comment by kostukp96** [comment] 2021-01-02 13:28
I ask you to tell me what exactly needs to be created in google cloud to launch this container ?

**Comment by untoldone** [comment] 2021-01-02 22:49
The readme gives you a one-liner for doing this at the very top of it. It explains all the variables needed. If you have a specific part of the readme you're having trouble with that you can point out, I would be happy to help.

"cloud run" and "cloud functions" are not docker specific and not related to this project, so if they are technologies you wish to use, unfortunately, I will not be able to help you with them. This project was intended to be run on docker being run directly on a GCP compute instance which has been granted full API access / access to dns + certs + the lb you're working with.

**Comment by kostukp96** [comment] 2021-01-04 14:50
Could you tell me what is the name of this docker on dockerhub?

I understand that I need to create a virtual machine, install a docker on it and then run a dockerfile?

**Comment by untoldone** [comment] 2021-01-04 16:45
It is bloomapi/letsencrypt-gcloud-balancer ... could you please read the README here... the image name is listed on the second line of it as well as gives details on all the parameters that are needed to run it successfully.

**Comment by kostukp96** [comment] 2021-01-11 11:30
Hello! Can you tell me how to keep this container running? After I enter docker ps, I do not see running containers

**Comment by untoldone** [comment] 2021-01-11 17:06
If configured correctly, it will keep itself running

**Comment by kostukp96** [comment] 2021-01-11 17:16
but when i run this command "docker run --env GCE_PROJECT=gcp-project-name --env LETSENCRYPT_EMAIL=my@email.com --env TARGET_PROXY=name-of-gcp-target-https-proxy --env DOMAINS_LIST="-d domains.list -d where.each -d is.prefixed.by.a.dash.d" bloomapi/letsencrypt-gcloud-balancer" and run "docker ps" i cant see any container

**Comment by untoldone** [comment] 2021-01-11 17:44
I'm sorry, but this sounds like we're walking through some basic docker debugging steps. If you're able to point to a specific bug or issue that was likely caused by an issue in this project, I'd be happy to help, but without direct evidence of the issue being with this project, I can't help given my own time constraints.
